# Generated by Django 3.2 on 2021-05-07 15:45

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(default='No Description', max_length=500)),
                ('date_posted', models.DateTimeField(verbose_name=datetime.datetime(2021, 5, 7, 15, 45, 26, 751794, tzinfo=utc))),
                ('PDFfile', models.FileField(upload_to='PDFCollection')),
                ('comments', models.TextField(default='No Comments', max_length=500)),
                ('status', models.CharField(default='pending', max_length=10)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
