# Generated by Django 3.2 on 2021-05-07 15:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_posted',
            field=models.DateTimeField(verbose_name=datetime.datetime(2021, 5, 7, 15, 50, 44, 815269, tzinfo=utc)),
        ),
    ]
