# Generated by Django 3.2 on 2021-05-08 15:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_post_date_posted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_posted',
            field=models.DateTimeField(verbose_name=datetime.datetime(2021, 5, 8, 15, 33, 12, 943101, tzinfo=utc)),
        ),
    ]
